name: start
on: push
jobs:
  setup:
    name: Setup project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
  test:
    needs: setup
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: make test
  lint:
    needs: [setup, test]
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - run: make lint
