name: start
on: push
jobs:
  setup:
    name: Setup project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start install and build project
        run: make setup
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
